DYNAMIC_MACRO_ENABLE = no
LEADER_ENABLE = no
NKRO_ENABLE = yes
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE   = no

# Firmware size Optimizations
EXTRAFLAGS += -flto
SPACE_CADET_ENABLE = no
SPLIT_KEYBOARD    = no
UNICODEMAP_ENABLE = no
